version: '3'

services:
  web:
    build: ./docker/web
    ports:
    - 80:80
    volumes:
    - ./my-site:/var/www/html
    depends_on:
    - db

  db:
    image: mysql:5.7
    environment:
    # - MYSQL_ROOT_PASSWORD=rootk
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=db
    # - MYSQL_USER=root
    # - MYSQL_PASSWORD=pass
    ports:
    - 3305:3306
    volumes:
    # 初期データを投入するSQLが格納されているdir
    # - ./db/mysql_init:/docker-entrypoint-initdb.d
    # 永続化するときにマウントするdir
    # - ./db/mysql_data:/var/lib/mysql
    - db-mysql:/var/lib/mysql
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_unicode_ci


volumes:
  db-mysql:
